### ISSUE TITLE
Publish token data

### ISSUE THREAD

**Issue by with-heart** [Developer-DAO/developer-dao#101]
I've seen a number of uses of the data related to the DevDAO token (traits, $DEV token combinations, etc.) in this project, `pixel-avatars`, and other community projects. It'd be nice to create an official package that exports this data, so all of the projects can reference the same thing rather than duplicating it all over the place. Maybe `@developer-dao/data` or `@developer-dao/token`?

**Comment by Dhaiwat10** [comment]
I'd absolutely be down for this. Is this data constant/static, or do we have to read it from the mainnet? (maybe we can cache it?)

**Comment by thomasmetta** [comment]
Maybe we can leverage The Graph?

**Comment by gjsyme** [comment]
I am taking a look at the Graph. Not sure if anyone can view this yet due to not being published: https://thegraph.com/studio/subgraph/devs-for-revolution-(devs)/ (nor super sure it solves anything).

**Comment by gjsyme** [comment]
Inspired by #92 I put together a script that can enumerate or serve a simple local API for data about different tokens that may be useful on this: https://github.com/gjsyme/hh-devs-for-revolution

**Comment by codingwithmanny** [comment]
@with-heart @gjsyme  I actually have a pull for all this data. I wanted to make sure I got data directly from the source as much as possible to avoid any discrepancies. I used Etherscan to make requests to the contract for all attributes (getClothing,... tokenURI), for all 1 to 8000 ids.

If interested I create a PR for it.

**Comment by codingwithmanny** [comment]
If you'd like to see the proposed data, see:
https://developer-dao-9r0tv1fhw-developdao.vercel.app/devdao-data.json.zip
