### ISSUE TITLE
Update README.md to give more detail on DeveloperDAO

### ISSUE THREAD

**Issue by kempsterrrr** [Developer-DAO/developer-dao#11]
I expect this repo could get a fair bit of exposure in the next few days & weeks so think it would be good to update our README.md to provide more info.

I'm happy to spin up a PR for this to get the ball rolling will get this up tomorrow. Keen for input on what to include but probably start with:

- Brief overview of DeveloperDAO (given the what/why is still being defined)
- Instructions on how to join
- Some info on web3/DAOa, probably safe to assume many people seeing this wont
- Link to contribution page being discussed in #9 
- Section to display contributors

**Comment by thomasmetta** [comment]
Sounds good

**Comment by with-heart** [comment]
I think this is a solid idea. Get it off the ground with a basic set of information to help newbies understand what this project is and how to connect with us, and then we can evolve it as we move forward.

**Comment by with-heart** [comment]
btw wanted to share the "Community" section of the BlitzJS docs for inspiration: https://blitzjs.com/docs/how-the-community-operates

I love that it paints such a clear picture of like how the blitz community operates, expectations and such for contributors and maintainers, how to become a maintainer, ways to contribute and become involved, etc.

Good inspiration for how we could document the DAO as a whole, but I think there are a lot of things that can be applied specifically to our README too.

**Comment by kempsterrrr** [comment]
> btw wanted to share the "Community" section of the BlitzJS docs for inspiration: https://blitzjs.com/docs/how-the-community-operates

This is dope. I've raised the question elsewhere about starting to build some docs for the DAO which they can then host on Gitbooks (hopefully for free). Guess there is a community decision to be made about the purpose of our main website and where to host this info. Need to get governance (proposals and voting etc) rolling asap! 

My intention is the following structure
LOGO
Developer DAO
one liner about community
What is a DAO
What is DeveloperDAO
How to join us?

Getting started with this repo
 - prerequisites
 - installation
Contributing
Contributors

Anyone have thoughts on this? What's missing/should be removed?

Will push a PR shortly. The text explaining what is DAO and DeveloperDOA etc. is mainly being pulled from what has been said in the community already although I'm sure this will evolve. Only a few days in !

**Comment by kempsterrrr** [comment]
Pushed up a V1 to get things rolling. L

This is all pretty new to me... I've never created something like this that's going to have so many public eyes on it before!

Current structure is:

- Table of Contents
- What is a DAO
- What is DeveloperDAO
- How do I join?
- What is this repo?
- Developing
- Contributing
- Authors

Things I think we need to add but need community input:

- Lisence
- Code of Conduct

https://github.com/alexvanzyl (@with-heart please add to repo) heard back from Netlify re their free open source offer and it speaks about need both of the above. Here is a link to the [T&Cs](https://www.netlify.com/legal/open-source-policy) and [message](https://discord.com/channels/883478451850473483/885402501900283935/885559715642359908) in discord.

I do love the Blitz example above, probably should have incorporate it more just wanted to things rolling.

Love any feedback and suggestions!

**Comment by alexvanzyl** [comment]
@kempsterrrr went over the `README.md` file, for what it's worth looks good to me as a starting point, some minor typos but looks like @xdrdak has already caught them :smile:.  I think at a later stage the "What is DeveloperDAO?"  can be expanded as the community forms more of an identity.

With regards to hosting whatever the final decision is there happy to help get things set up.

**Comment by kempsterrrr** [comment]
thanks @alexvanzyl ! I'm with you on the `What is DeveloperDAO` section 💯, feeling is this is going to evolve once we get organised around a why. IMO the first part is OK but I don't particularly like this

`As stated on : "Developers around the world are tired of working and contributing their time and effort to enrich the top 1%. Join the movement that is community owned, building the future from the bottom up."`

Al the first bit `As stated on `: doesn't make sense 😂  Thoughts on just removing that section? 

Will make correct the typo's and push up an amended version now.

**Comment by kempsterrrr** [comment]
Solved in #13
