### ISSUE TITLE
Project Produced By

### ISSUE THREAD

**Issue by codingwithmanny** [Developer-DAO/developer-dao#113]
**Context:**
Seen it a few times where people were asking who worked on what project and didn't know.

**Proposal:**

*Edit: On the `/projects` page (and any translated page `/es`, `/fr`, etc)

Option 1 - Add the github username:

```md
[Developer DAO](https://developerdao.vercel.app/) - by [fmoliveira](https://github.com/fmoliveira)
```

Option 2 - Add name when username not available:

```md
[Developer DAO](https://developerdao.vercel.app/) - by Filipe Oliveira
```

**Work Needed**
- [ ] Find there github usernames for the projects to link to them
- [ ] Modify the `projects` page
- [ ] Add translations for `by` in the common.json files (coordinate to get as many official languages as possible)

**Questions:**

👍 If you like this idea (we should do it)
👎 If you don't like this idea (aka don't do it)
🆕 If you have a different proposal

**Comment by Dhaiwat10** [comment]
That sounds like a great idea!

I believe this is to be added to the `/projects` page?

**Comment by codingwithmanny** [comment]
@Dhaiwat10 that's right, it would be to the Projects page. I'll clarify that.

**Comment by Nazeeh21** [comment]
I would like to work on this.
