### ISSUE TITLE
Update deployment/hosting

### ISSUE THREAD

**Issue by thomasmetta** [Developer-DAO/developer-dao#12]
Currently, auto deployment is not working since this project was moved to an Org instead of a personal account. We need teams on vercel to get the deployment working again; however, that's a paid tier. 

We need to find another hosting solution for deployment. Any suggestion is welcome

**Comment by sankalpk** [comment]
render.com has a free tier and it worked pretty well for me in previous projects.

**Comment by kempsterrrr** [comment]
Given we are are a community for thousands of developers we may be able to get vercel to give us free / discounted hosting fro the main website as free publicity for them. [Netlify](https://www.netlify.com/) also do this.

Think it is definitely worth reaching out to them and happy to do so. Thoughts? and would we prefer Vercel or Netlify, or another?

**Comment by with-heart** [comment]
@kempsterrrr Definitely worth it! Vercel has a free plan for open source projects, so we should be covered by that if someone reaches out to them.

**Comment by Dhaiwat10** [comment]
Has anyone reached out to them yet?

**Comment by kempsterrrr** [comment]
Yes, see [here](url). We have the OK from the DevRel team as long as meet these T&Cs - https://vercel.com/support/articles/can-vercel-sponsor-my-open-source-project

I'm starting to think we just push on with Vercel. Thoughts everyone?

**Comment by Dhaiwat10** [comment]
Vercel is great! We should def be looking to get their services if it's possible for us.

Will a static site be enough for us tho? I'm pretty sure we meet the rest of the criteria.

**Comment by thomasmetta** [comment]
Quick update on this. We moved to team in vercel, will sort out the sponsorship soon
