### ISSUE TITLE
Add allcontributors 

### ISSUE THREAD

**Issue by with-heart** [Developer-DAO/developer-dao#15]
[allcontributors](https://allcontributors.org/) is a great way for us to recognize contributors to the project. It also allows us to be more specific than GitHub contributors in that it shows the specific types of contributions each contributor has made.

**Comment by kempsterrrr** [comment]
Yup. Totally into this. Shall I include in #13 ?

**Comment by thomasmetta** [comment]
let's do it

**Comment by kempsterrrr** [comment]
Added app to org, see below need someone with higher privs to authorise on this repo. 

![Screenshot 2021-09-11 at 04 24 15](https://user-images.githubusercontent.com/9025997/132934677-4405a546-7ba4-4dd9-bab5-47cb924c94f9.png)

**Comment by thomasmetta** [comment]
Done
