### ISSUE TITLE
Design Proposal 2020-09-11

### ISSUE THREAD

**Issue by codingwithmanny** [Developer-DAO/developer-dao#20]
**Context:**
Reason for this design to give the public links to social links, and a quick url to the github repo for this website.
This is of course a discussion and not the end all of what needs to be implemented. This is just a proposal to start the discussion.

**Features:**

A - New top navigation, includes potential links for other pages, and a github icon which links to this repository (in case they want to contribute)

B - New footer that includes the following links:
1 - [OpenSea](https://opensea.io/collection/devs-for-revolution) - https://opensea.io/collection/devs-for-revolution
2 - [Etherscan](https://etherscan.io/address/0x25ed58c027921e14d86380ea2646e3a1b5c55a8b) - https://etherscan.io/address/0x25ed58c027921e14d86380ea2646e3a1b5c55a8b)
3 - [Twitter](https://twitter.com/developer_dao) - https://twitter.com/developer_dao
4 - [Discord](https://discord.gg/zRnZpzzY) - https://discord.gg/zRnZpzzY

**Small Note:**
Until I figure out what fonts are used for the logo, site, and more, I put rectangle blocks to represent the text for now.

**Before:**
![Before-2020-09-11](https://user-images.githubusercontent.com/318082/132954610-dfe487e1-3f76-4c05-b359-2c7c319a7eb4.png)

**Proposal:**
![Proposal-2020-09-11](https://user-images.githubusercontent.com/318082/132954618-31934568-4fff-4b89-b8ca-dbb7e9062532.png)

**Comment by aesthytik** [comment]
@codingwithmanny the website is using tailwindcss with system default fonts.

**Comment by codingwithmanny** [comment]
thanks @aesthytik I figured. Just need to figure out the way to get those fonts downloaded again. I can't remember the link for them, but I'll give it a look.

If anyone happens to know the font used for the D_D logo, that would help immensely as well.

**Comment by with-heart** [comment]
@codingwithmanny This looks great! It's a nice way to present a lot of relevant information on the screen. The menu bar is especially nice.

**Comment by with-heart** [comment]
Unfortunately I'm not sure what the font is either :( We'll get it figured out at some point though

**Comment by codingwithmanny** [comment]
I'm 90% sure the system font it's SF Pro Text from https://github.com/supermarin/YosemiteSanFranciscoFont on my system.
<img width="1368" alt="Screen Shot 2021-09-11 at 5 28 11 PM" src="https://user-images.githubusercontent.com/318082/132962037-9b9da143-0a9f-4fd5-a927-dfd26bc43bfc.png">

I might suggest using a more specified font like Roboto, Poppins, Inter or Open Sans.

**Comment by codingwithmanny** [comment]
Here is the revised design proposal.

Let me know with a 👍 if you think I should implement this or discuss further.

**Before / Current**
![Before-2020-09-11](https://user-images.githubusercontent.com/318082/132963631-06f9f99c-2544-499b-a911-970e55d5e70c.png)

**Proposal**
![Proposal-2020-09-11](https://user-images.githubusercontent.com/318082/132963634-380e8cc2-4e15-4b7e-8ae0-5ee80531ef2e.png)
