### ISSUE TITLE
ViteJS vs CRA

### ISSUE THREAD

**Issue by codingwithmanny** [Developer-DAO/developer-dao#22]
**Context:**
This is more of a discussion thread to see what everyone thinks about converting this to [vitejs](https://vitejs.dev) that runs on [esbuild](https://esbuild.github.io). If anyone has used vitejs or esbuild, as a dev you will see dramatically the difference in build time for local development and deployments.

**Reasons For:**
1 - Speed for local development
2 - Simplified process

**Reasons Against:**
3 - If Vercel's build process completely doesn't support it, that I don't know, but then again it's just React.
 ̶4̶ ̶-̶ ̶T̶i̶m̶e̶ ̶t̶o̶ ̶r̶e̶f̶a̶c̶t̶o̶r̶ ̶t̶h̶e̶ ̶c̶o̶d̶e̶ (See PR #27)
5 - If there are special packages used for CRA, but most of them seem agnostic at the moment

**Comment by nheingit** [comment]
I haven't used Vite myself, but know several people that swear by it. It's easier to do this now rather than later.

The biggest downside here I think will be barrier to entry to contributing, as people are more familiar with CRA. However I'd be in favor for a move to vite.

Would be interested if @with-heart has any strong opinions on this.

**Comment by codingwithmanny** [comment]
Without trying to overly commit. I could maybe (bigger maybe), create a proposal.
But would need to coordinate with whoever did the vercel deployments.

**Comment by Dhaiwat10** [comment]
Personally, I'm a huge fan of Vite but whether we should make the move to it depends on what we plan to do with this codebase in the future  — what 'features' we might add, whether it will be _mostly_ static like right now or not?

If we are planning to build a load of features on top of this codebase, I'd say we're early enough to afford a re-factor. Would love to hear everyone else's thoughts :)

**Comment by kempsterrrr** [comment]
I'm not against this, also heard many good things about Vite. Can I add Next.js into the conversation?

Reasons for:
- tight integration with Vercel
- sane defaults for routing, images, data-fetching etc.
- easy onboarding

Reasons against:
- even more substantial refactor
- slower build times compare the esbuild

**Comment by codingwithmanny** [comment]
I just did the conversation, minus some tests. I'm creating a PR to review, but I may need some help on some things.

**Comment by codingwithmanny** [comment]
@kempsterrrr I thought about this too. I realize it's experimental, but there's also SSR with Vitejs (just haven't tried it personally yet):
https://vitejs.dev/guide/ssr.html#conditional-logic

**Comment by kempsterrrr** [comment]
Interesting. @Dhaiwat10 any experience with ssr and Vite?

I think the point about what we do with the website is important too but also we don't want it to slow us down. There has been some chatter about building a web3 course platform in discord [here](https://discord.com/channels/883478451850473483/884358142257938452/884750647684136990) which I think is a pretty dope idea!

Guess it could end up being anything though which itself is probably something to consider re this decision. I'd normally opt for batteries included for core features like routing, ssr and data fetching if it were my choice alone. But also I'm down for what majority wants to do :)

**Comment by with-heart** [comment]
> Would be interested if @with-heart has any strong opinions on this.

Not really! Just biases towards what I'm familiar/comfortable with. Next.js has been my default go-to for a while now, but I've also heard wonderful things about vite and am totally open to learning something new if that's the route we want to go.

Does anyone know how something like `mdx` setup and configuration works with vite? Like what that looks like code-wise? Would love to see a good modern vite site setup, just to familiarize myself with it.

**Comment by will-t-harris** [comment]
I haven't used it so can't vouch for it, but there's [this Vite plugin] for mdx that seems active.

I've messed around with Vite a bit in the past and was _very_ impressed with how quick the local dev feedback loop is. Almost imperceptible HMR times.

**Comment by Dhaiwat10** [comment]
@kempsterrrr if we need SSR, I think Next.js is by far the best solution out there. Like @codingwithmanny said, support for SSR in Vite is experimental. I have tried it, I haven't faced any major issues but I don't we should rely on it. I would much rather rely on Next.js.

**Comment by codingwithmanny** [comment]
This might be a sideways opinion, but if the goal is to have static generated pages that are SEO friendly and we don't intend to pull from a database or a CMS often, I might suggest using Gatsby.

Unless you everyone is suggesting SSG with NextJS?

**Comment by kempsterrrr** [comment]
imo static is the way to go whatever we chose as right now we just need a basic site. Think here's also a good chance we'll want/need dynamic functionality in the not-too-distant future so also should probably factor that in now.

Gatsby is a-ma-zing for small (*not v large) static sites like blogs etc. (use it for mine) but my understanding is once you try to go too dynamic and/or scale-up it's less effective (long build times, not very DX friendly for dynamic sites).

Re Next + SSG... I see it as SSG by default and then you can incrementally adopt SSR when you need it. Haven't worked anything massive with it though tbh.

Did a little googliweb, this came up - [vite-plugin-ssr](https://vite-plugin-ssr.com/) - with the tag line `Like Next.js / Nuxt but as do-one-thing-do-it-well Vite plugin.`. Looks interesting but like @will-t-harris can't vouch.

**Comment by codingwithmanny** [comment]
> Gatsby is a-ma-zing for small (*not v large) static sites like blogs etc. (use it for mine) but my understanding is once you try to go too dynamic and/or scale-up it's less effective (long build times, not very DX friendly for dynamic sites).
100% agree. Maybe not Gatsby then.

> Re Next + SSG... I see it as SSG by default and then you can incrementally adopt SSR when you need it. Haven't worked anything massive with it though tbh, mainly enjoy the sane defaults re routing, data fetching, images etc.
Did we want to create a proposal then? 

> Did a little googliweb, this came up - [vite-plugin-ssr](https://vite-plugin-ssr.com/) - with the tag line `Like Next.js / Nuxt but as do-one-thing-do-it-well Vite plugin.`. Looks interesting but like @will-t-harris can't vouch.
I'm quite good at googliwebs as well :)
I could spend a little time later this weekend looking at the vite ssr implementation, if everyone thinks it's worth looking into.
I have to finish writing 3 blog articles on esbuild for work, so it wouldn't be that far off to look into at the same time.

**Comment by codingwithmanny** [comment]
Tried to convert the draft vitejs with the `vite-plugin-ssr`... kind of more like do-one-thing-do-it-not-quite-there-yet-so-well.
Documentation is off, sample code doesn't seem to match, some functions aren't even recommended anymore when you try to compile it,  and when I did get it to compile the page flashes for html rendering. 

Don't mean to be negative, but objectively this doesn't encourage confidence.

IMO, we should start looking at Next if we're taking the route of SSG.
Who knows maybe Next we'll try and incorporate esbuild/vitejs in the future.

**Comment by will-t-harris** [comment]
Thanks for looking into that @codingwithmanny 

Vercel did just recently hire the author of webpack, so I'd assume they will continue to rely on webpack for the foreseeable future.

Not necessarily a bad thing, but did want to throw that out there.

**Comment by codingwithmanny** [comment]
Just going to close this issue because it looks like we need to discuss in another thread regarding NextJS as a proposed implementation.
