### ISSUE TITLE
Empty prettier config

### ISSUE THREAD

**Issue by Dhaiwat10** [Developer-DAO/developer-dao#26]
The [prettier config file](https://github.com/Developer-DAO/developer-dao/blob/main/.prettierrc.json) is...empty? 😅

Shouldn't we have some rules in place inside the config?

**Comment by codingwithmanny** [comment]
Good call. Here's my initial proposal:

```json
{
  "printWidth": 80,
  "tabWidth": 2,
  "useTabs": false,
  "semi": true,
  "singleQuote": true,
  "trailingComma": "all",
  "proseWrap": "always"
}
```

**Comment by Dhaiwat10** [comment]
LGTM! I'll put in a PR once we get a few more green lights :)

**Comment by with-heart** [comment]
Go for it!
