### ISSUE TITLE
Replace Logo With SVG

### ISSUE THREAD

**Issue by codingwithmanny** [Developer-DAO/developer-dao#35]
**Context:**
Instead of representing the logo as a jpeg. I would like to propose the loge in the format of SVG.

**Reasons:**
- Typically smaller in size
- Can scale (because it's a vector)

**Problem:**
I couldn't find the font to recreate the logo, so I redid the logo in Figma as close as possible.
Link to Figma file: https://www.figma.com/file/BBxYJrArJFOpND9c4OBWkY/D_D?node-id=3%3A2

**Proposed:**
Here is a side by side with the original jpg, vector, and then the vector on top of the jpg to show the difference.
<img width="1280" alt="Screen Shot 2021-09-11 at 6 29 21 PM" src="https://user-images.githubusercontent.com/318082/132963122-06d55541-1376-4381-90d5-8d7e41fe32e2.png">

I would also propose that in the main `App.jsx` it be turned into the following:

**File:** `src/App.jsx`

```diff
  return (
    <>
      <section className="text-gray-600 body-font">
        <div className="container mx-auto flex px-5 py-24 items-center justify-center flex-col">
-          <img
-            src={logo}
-            alt="hero"
-            className="mb-5 w-32 h-32 object-cover object-center rounded-full"
-          />
+         <Logo className="mb-5 w-32 h-32 object-cover object-center rounded-full" />
```

**File:** `src/Logo.jsx` *NEW

```jsx
import React from 'React';

const Logo = ({ className }) => <svg className={className} ... />;

export default Logo;
```

**Comment by with-heart** [comment]
Let's do it!

**Comment by aesthytik** [comment]
Awesome, looks good

**Comment by kempsterrrr** [comment]
looks good!

**Comment by with-heart** [comment]
@allcontributors please add @codingwithmanny for design
