### ISSUE TITLE
Caching Mechanism For Token Metadata

### ISSUE THREAD

**Issue by codingwithmanny** [Developer-DAO/developer-dao#37]
**Context:**
I can imagine there being a wall or gallery view of all the token's that have been issued, similar to when viewing: https://opensea.io/collection/devs-for-revolution that we might want to show later on a different page or use to show other data.

**Problem:**
Querying all this data each time is expensive when querying each token directly.

**Solution:**
Considering that all tokens are static (excluding ownership), their data won't change.
Create an script that would ping every individual token and generate a local json file to be used by the site.

**Comment by will-t-harris** [comment]
Agreed that a local json file sounds like the simplest approach here.

**Comment by codingwithmanny** [comment]
Just mentioning here that I am working on this.
My be taking a bit longer because I didn't want to just copy and paste json from another service.
I wanted a script that we could use later for other various contract to pull in information via a cli tool.
Not entirely sure that still entirely feasible but I have been playing around with etherscan's API.

**Comment by fmoliveira** [comment]
@codingwithmanny

Would this help? https://github.com/Anish-Agnihotri/dhof-loot/blob/master/index.js

**Comment by codingwithmanny** [comment]
@fmoliveira this helped a lot. I managed to get inspired from it and created a script that relies on etherscan's api to pull in the data. Much appreciated 🙏

**Comment by codingwithmanny** [comment]
Decided to close this issue so that a new repository could be made instead to host this script.
