### ISSUE TITLE
Add "copy link" button for linking directly to NFT id

### ISSUE THREAD

**Issue by with-heart** [Developer-DAO/developer-dao#44]
Following up on #38, it'd be useful to allow users to click a button to copy the URL to the current NFT. Makes it much easier to share with others, and makes it obvious to them that the functionality exists.

**Comment by Dhaiwat10** [comment]
I'll take up this one too since no one has yet 👍🏻

**Comment by codingwithmanny** [comment]
Closing this because it was addressed in #79
