### ISSUE TITLE
Switch to a component library

### ISSUE THREAD

**Issue by with-heart** [Developer-DAO/developer-dao#47]
I think we should consider using a modern, accessibility-driven component library as the basis for the site. I love `tailwind` but it only gives us a design system. Which is important, but it's only just barely scratching the surface of our needs.

# Benefits

- lots of pre-built components that encapsulate the basic functionality that exists in most apps
- a11y is one of the most important things for building a site that users love and find pleasing to use
	- visual consistency, accessible colors and font sizes, etc.
	- component behavior that matches user expectations
		- relationships between various parts of the component
		- keyboard shortcuts
- easy to style using theme, props, etc.
- building a component library is a ton of effort to do, and even more effort to do well
	- whether we're intentional about it or not, we end up with a component library
	- why not offload that effort to an open source team that has already done all of the work and will continue to do the maintenance in the future?

# Possible Libraries

- [Chakra UI](https://chakra-ui.com/)
- [Radix UI](https://www.radix-ui.com/)
- [React Spectrum](https://react-spectrum.adobe.com/react-spectrum/)

**Comment by with-heart** [comment]
This isn't supposed to be empty. Hit submit too early. Check back later! 😁

**Comment by xdrdak** [comment]
Agreed on using a component library. Lot's of choices out there though...

My vote would be to go for chakra-ui. It's pretty much battle tested and has a large enough community around it (plus I loved using it so big props to you @with-heart + the chakra community). 

Sure, we can do something dope with tailwind + a headless component library, but I think it's a good idea to start streamlining certain things (like components and stuff) before we go into the weeds of rolling out component lib. Also, we don't need to publish much if we use Chakra, perhaps just a few add-on components or a theme file. This'll allow us to get something out fast and proper so we can shift focus on other thangs (governance perhaps?).

There's a few PRs in flight right now, but I can begin by transitioning existing stuff to Chakra and just use `sx` props for now until we get a design going.

**Comment by kempsterrrr** [comment]
+1 for Chakra UI. Used Tailwind a lot but recently moved to Chakra and found it much nicer + you get a lot more for free and preferred their approach using props + values over classes. That said, I've only used the built in styles although the docs for custom styling make it look pretty neat.

Can't common on the others but assume they solve similar problems.

Imagine it can't hurt having @with-heart here also 😉

**Comment by thomasmetta** [comment]
Chakra UI since @with-heart is here lol

**Comment by with-heart** [comment]
That's totally fair. I'm obviously biased in a certain direction so don't want to pressure the project to move that way, but if there are enough of us that prefer it/feel comfortable with it, I think it'll be a good choice for us!

**Comment by with-heart** [comment]
btw Chakra has a free egghead.io course available now. If you're reading this and haven't used it before, it's a great resource for getting started! https://egghead.io/courses/build-a-modern-user-interface-with-chakra-ui-fac68106

**Comment by Dhaiwat10** [comment]
I'd also vouch for chakra-ui. Has always served me well, can never go wrong with it :)

**Comment by gjsyme** [comment]
i can do this on chakra. will get something out tonight, but then i will disappear for 5 days, so hopefully it's an acceptable product.

**Comment by with-heart** [comment]
@gjsyme Do what you can! I'll cover the rest if it's not quite to the finish line

**Comment by with-heart** [comment]
Closing this in favor of #60
