### ISSUE TITLE
Add Community Projects section to website

### ISSUE THREAD

**Issue by kempsterrrr** [Developer-DAO/developer-dao#48]
I think we should have a home on the website to showcase tools being built by the community. Don't know if we want to wait for #45 merged first and potential #47 to be addressed but wanted to get this up here so it's on our radar. Either way, I'd be happy to take it on if/when we agree it's a good idea.

## Projects

- http://ddao.ibby.dev/ - IbbyDev {#1703} | IbbyDev#8201
- https://developerdao.vercel.app/ - fmoliveira#3333

I'm sure there were more than this.... please add if I've missed any

**Comment by codingwithmanny** [comment]
My suggestion for this, before any code is done, is to create either a quick wireframe or quick design file of what this section would look like.

**Questions:**
1 - Should it be a list or grid of thumbnails?
2 - Should there be filtering?
3 - Should "Projects" be in the navigation bar?
4 - When you click on a project, does it lead to the repository, a project url, other?

**Comment by with-heart** [comment]
Good points+questions @codingwithmanny!

1. Probably start with a list? I think we need more projects to figure out how to best represent them.
2. Eventually but probably not needed to start. Not enough there to even justify filtering at this point.
3. Ye
4. Project URL. The project itself should link to its own repo, etc.

**Comment by Nazeeh21** [comment]
I want to work on this feature

**Comment by codingwithmanny** [comment]
@Nazeeh21 because it's a new page, did you want to tackle the wireframe of what that page might look like first?

**Comment by Nazeeh21** [comment]
Yes, I do. Infact, I was about to ask for that.

**Comment by codingwithmanny** [comment]
Sounds good.

**Comment by Nazeeh21** [comment]
@codingwithmanny  I have designed a UI for the Projects page [here](https://www.figma.com/file/23EfsfC1YAQJ0KBlbpZpoV/Untitled?node-id=0%3A1). Please have a look and do provide me suggestions.

**Comment by codingwithmanny** [comment]
Hi @Nazeeh21 just to keep the look consistent with the website.
Perhaps you could use this base [https://www.figma.com/file/BBxYJrArJFOpND9c4OBWkY/D_D?node-id=37%3A3](https://www.figma.com/file/BBxYJrArJFOpND9c4OBWkY/D_D?node-id=37%3A3)
Take a look at **Website Proposal 2021-09-15** there's a page I started a couple days back to try and address. Perhaps you could copy the Figma file and go from there.
Let me know what you think.

**Comment by Nazeeh21** [comment]
> Hi @Nazeeh21 just to keep the look consistent with the website.
> Perhaps you could use this base https://www.figma.com/file/BBxYJrArJFOpND9c4OBWkY/D_D?node-id=37%3A3
> Take a look at **Website Proposal 2021-09-15** there's a page I started a couple days back to try and address. Perhaps you could copy the Figma file and go from there.
> Let me know what you think.

Sure, I'll start from this boilerplate.

**Comment by Nazeeh21** [comment]
I have designed the Projects page from the provided boilerplate. Please provide suggestions.
FIgma link: https://www.figma.com/file/23EfsfC1YAQJ0KBlbpZpoV/Untitled?node-id=9%3A35

**Comment by codingwithmanny** [comment]
@Nazeeh21 looks like a good base to me. Keep us posted on the PR.
Just remember to mention in the PR `Fixes #48`
Other than that, looks like a good direction.
