### ISSUE TITLE
Fix README.md logo

### ISSUE THREAD

**Issue by codingwithmanny** [Developer-DAO/developer-dao#50]
**Context:**
When the new logo as an svg was merged down it broke the `README.md` file with reference to the old jpg.

**Before:**
<img width="2032" alt="Screen Shot 2021-09-14 at 4 13 31 AM" src="https://user-images.githubusercontent.com/318082/133221162-8e09fc19-7e4a-4f5d-9785-bdc688f75358.png">

**Proposal:**
Propose using the `public/logo512.png` as the base.

**Comment by with-heart** [comment]
Go for it!

**Comment by with-heart** [comment]
Meta note: I feel like we should carve out an exception to the "open an issue and seek validation before working" rule for minor technical tasks like this. Same PR + the contents of this issue as its description would have been totally fine without needing to open an issue imo.

**Comment by codingwithmanny** [comment]
@with-heart but I like closing issues 😂

**Comment by with-heart** [comment]
lol that's fair, whatever floats your boat!
