### ISSUE TITLE
(mobile) Styling breaking for the owner display

### ISSUE THREAD

**Issue by Dhaiwat10** [Developer-DAO/developer-dao#54]
### Context

![Screenshot](https://user-images.githubusercontent.com/39617427/133275179-bcbd59e4-316d-4405-9d03-aeeecd1fab9a.jpeg)

Captured on an Android device, Chrome browser.

**Comment by miralsuthar** [comment]
I would like to contribute to this

**Comment by Dhaiwat10** [comment]
@miralsuthar all yours
