### ISSUE TITLE
i18n Metatags

### ISSUE THREAD

**Issue by codingwithmanny** [Developer-DAO/developer-dao#63]
**Context:**
Note this should be after we merge #57.
Whenever sharing links of the website, `/fr` or `/es` it does not show the translation of the title or description of the page in that native language. The goal would be to fix that with an existing library.

A conversation was had on potentially using `next/head` instead of `react-helmet`, as a reference.
https://stackoverflow.com/questions/61063193/react-helmet-or-next-head-for-next-js-project#61063491

**Current State:**
When debugging the french or spanish website with Facebook's sharing debugger, the following comes up:
[Link](https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fdeveloper-dao-lewqo5jyg-developdao.vercel.app%2Ffr) Note: link may expire, see screenshot as alternative.

<img width="2032" alt="Screen Shot 2021-09-14 at 6 38 27 PM" src="https://user-images.githubusercontent.com/318082/133343029-c5515171-e212-492c-823c-524eb5cbf482.png">

**Proposal:**
Implement a library that works with i18n and make sure it works with Facebook's sharing debugger.

**Comment by fmoliveira** [comment]
Hi @codingwithmanny , I'd like to work on this one!

**Comment by codingwithmanny** [comment]
Done.

**Comment by codingwithmanny** [comment]
@fmoliveira you should be good to go for this one.
