### ISSUE TITLE
Add direct opensea link to Dev name

### ISSUE THREAD

**Issue by narbs91** [Developer-DAO/developer-dao#67]
Even though we have a opensea link to the entire project itself in the footer, it would be useful to have a direct link to the searched developer after a successful search.  For example, the name "Dev 1" will link to https://opensea.io/assets/0x25ed58c027921e14d86380ea2646e3a1b5c55a8b/1

**Comment by narbs91** [comment]
I'll take up this feature

**Comment by aesthytik** [comment]
awesome @narbs91

**Comment by codingwithmanny** [comment]
@narbs91 the current link to the dev links to an etherscan URL, what would you like to propose for showing both links? Would you have a UI change to propose?

**Comment by codingwithmanny** [comment]
If `Dev#1` has a link to it, I might propose the following:

1 - If there is an owner then there show a link with an opensea icon next to it
2 - If there is no owner then there is no click through link and no opensea icon

Example for scenarios like the following:
[https://opensea.io/assets/0x25ed58c027921e14d86380ea2646e3a1b5c55a8b/7899](https://opensea.io/assets/0x25ed58c027921e14d86380ea2646e3a1b5c55a8b/7899)

<img width="2032" alt="Screen Shot 2021-09-15 at 6 22 50 AM" src="https://user-images.githubusercontent.com/318082/133416652-f8b6cdac-57ff-4e5f-aa20-8b45be2e502b.png">

**Comment by narbs91** [comment]
So what I was thinking in regards to implementation @codingwithmanny was exactly what you proposed:

If the NFT has an owner, turn the the name (i.e "Dev 1") to a link to it's given opensea link (https://opensea.io/assets/0x25ed58c027921e14d86380ea2646e3a1b5c55a8b/1)

if the NFT has no owner, the name appears without the link (as it is now)

UI wise, I thinking a button from the newly added [Chakra UI library](https://chakra-ui.com/docs/form/button):

![image](https://user-images.githubusercontent.com/29411347/133546339-593e3ac0-3269-407d-a54d-f4ebf56bc72f.png)

something like that but with the opensea mini icon.  The button would open in another tab

**Comment by narbs91** [comment]
Working Branch: https://github.com/narbs91/developer-dao/tree/feature/add_direct_nft_link

**Comment by codingwithmanny** [comment]
Yeah we can just mark the PR as a draft and see the progress.

**Comment by narbs91** [comment]
Cool, cool yeah sure.  I'll touch up the styling a bit today and open up a draft
