### ISSUE TITLE
Add unit test framework

### ISSUE THREAD

**Issue by narbs91** [Developer-DAO/developer-dao#68]
Need to add unit testing and potentially integration testing to the project

**Comment by codingwithmanny** [comment]
@narbs91 would you be able to describe a bit further what you'd like to propose, just to get a better idea. React-testing-framework, snapshots, cypress e2e, playwrite, etc?

**Comment by narbs91** [comment]
This is a bit of a loaded issue ;); however, i think this ticket should focus on adding unit testing for what has been implemented so far.  We can then open separate issues to add e2e tests and integration tests as well.   Framework wise, i'd have to research a bit but i figure something like [mocha](https://mochajs.org/)/[jest](https://jestjs.io/) and maybe [chai](https://www.chaijs.com/) as an assertions library.

The other thing that should be established is the "right" numbers for code/branch/line coverage.  Should we start with 80 percent coverage and tweak as we go?  i think anywhere between 70-80% coverage is usually the sweet spot but depends on the code base.

We should also, as part of this issue, add the tests as a hook and requisite to be run before a PR can be merged to main.  As well, we should add a checklist of items people should be reminded of doing as part of their PR (i.e making sure tests have been written, ensuring the app works as intended,  etc...)

**Comment by codingwithmanny** [comment]
- Agree: Unit tests for now, BUT I will say not snapshots if we plan on doing e2e later. I think it would be just a lost commitment.

- Agree: 80% coverage 

- Proposal: Just Jest, maybe React Testing Library (whichever works best with NextJS)

**Comment by with-heart** [comment]
> The other thing that should be established is the "right" numbers for code/branch/line coverage. Should we start with 80 percent coverage and tweak as we go? i think anywhere between 70-80% coverage is usually the sweet spot but depends on the code base.

Why should that be established?

**Comment by fmoliveira** [comment]
@with-heart 
> Has anyone used Cypress at all for e2e stuff before?

I have some experience with Cypress and general best practices.

Unless anyone is willing to grab e2e tests to work on, I would definitely love to contribute with Cypress!

@codingwithmanny I find React Testing Library super handy because it forces us to test in a more user-centered way, and not only because of that, but especially because there is also Cypress Testing Library! So, with Testing Library we will have pretty much the same lingo between unit, integration and e2e tests, for example:

Jest:
```js
// get element by accessible role and label text
screen.getByRole("input", { name: "Search developer DAO id" })
```

Cypress:
```js
cy.getByRole("input", { name: "Search developer DAO id" })
```

Note that both tests are looking for the input by its accessible role first and then its label text, which is a great benefit of Testing Library.

**Comment by with-heart** [comment]
I'm a big fan of `react-testing-library`! Definitely a solid direction to go in :)

**Comment by codingwithmanny** [comment]
Yeah I have experience with both, but if @fmoliveira wants to take it, that would take a load of my plate 😂

**Comment by fmoliveira** [comment]
@codingwithmanny 
> Yeah I have experience with both, but if @fmoliveira wants to take it, that would take a load of my plate 😂

That's tempting because I love cypress, lol 😆  I would be more than happy to take e2e! 😃

**Comment by narbs91** [comment]
Awesome discussion gang!  Coolio, so i'll move forward with just unit tests for this ticket but i'll dig into both jest and react testing library to get a better idea of which direction to go; however, sounds like the gang is into the react testing library so might lean that way.

@with-heart no worries at all, the code coverage number is a pretty loaded topic and often incorrectly set.  Basically we shouldn't just be writing tests for the sake of writing test but actually providing coverage that blankets the core functionality of the app and provides value as you say.  I agree with you that we should set up some guidance of what constitutes a "good" test and what's not, perhaps this is something we can look to add to our coding standards doc?.  Also, the 80 percent number is just somewhere to start and can be scaled up/down as we see fit
