### ISSUE TITLE
Check Chinese translations

### ISSUE THREAD

**Issue by with-heart** [Developer-DAO/developer-dao#69]
I'm an `en`-only kind of guy so I could be wrong here, but I was checking the existing translations and it looks like Chinese doesn't automatically load when my preferred language is set to `zh` or `zh-TW`. 

I think this is because the locale keys are incorrect. We're currently using `zhsc` and `zhtc` but I think this might need to be `zh` (simplified) and `zh-TW` (traditional). 

Could someone check this and see if it's working or not?

cc @kavimaluskam since you added the Chinese translations in #56

**Comment by kavimaluskam** [comment]
@with-heart Sorry that missing the part that the language is configured by browser preferred language.

I shall fix it later with the below language code then?
https://gist.github.com/wpsmith/7604842#file-browser-language-codes-js-L38-L42

**Comment by codingwithmanny** [comment]
Nice so @kavimaluskam you got this ticket?

**Comment by kavimaluskam** [comment]
Yep I double check and handle that, today.

**Comment by codingwithmanny** [comment]
All set! thanks!

**Comment by with-heart** [comment]
> I shall fix it later with the below language code then?

Yeah I think that should work! Thanks @kavimaluskam, appreciate you translating and helping out with getting this set up :)

**Comment by codingwithmanny** [comment]
Closing this because #70 fixes this.
