### ISSUE TITLE
Some text is too thin, hard to read

### ISSUE THREAD

**Issue by Dhaiwat10** [Developer-DAO/developer-dao#72]
![image](https://user-images.githubusercontent.com/39617427/133533799-30039b08-1f2d-45e8-83fa-ebde9c0117a1.png)

Anyone else feel that the underlined text is a bit too 'thin' & hard to read? I tested this on multiple devices and I feel we should definitely increase the font weight by atleast a bit.

**Comment by with-heart** [comment]
Definitely agree! I left text at the default font weight in #60 so I'll attach this issue to that :)
