### ISSUE TITLE
Add e2e tests with Cypress

### ISSUE THREAD

**Issue by fmoliveira** [Developer-DAO/developer-dao#75]
As discussed in another issue starting from this comment: https://github.com/Developer-DAO/developer-dao/issues/68#issuecomment-920887894 , we are willing to add e2e tests.

On that thread, we only mentioned Cypress and didn't discuss any alternatives. Apparently, that's the framework that we have more people familiar with it, and for me, personally, this is enough reason to pick Cypress – to use our current knowledge. And Cypress is very mature and has a vibrant community as well.

Anyone has something to add on this point – like proposing alternatives and comparison with Cypress? What does everyone think?

**Comment by fmoliveira** [comment]
I would love to work on this, by the way! 👀

**Comment by codingwithmanny** [comment]
@fmoliveira would you be able to confirm that this would work in GitHub actions? I believe it does support Docker, I even think I did something like for cypress tests and github actions.

If so, can you confirm that this would be built into this functionality as well?

**Comment by with-heart** [comment]
@codingwithmanny Ye they support all of the Actions things: https://docs.cypress.io/guides/continuous-integration/github-actions#Caching-Dependencies-and-Build-Artifacts

**Comment by fmoliveira** [comment]
Yeahh, the actions are really great! 🎉 

So it'll be ok to include a GitHub workflow right away with this issue, right? I initially thought of discussing the actions in a new issue because of the usage quota (2000 minutes on a free GitHub account), but since you've already mentioned it, yes, I do think it makes a lot of sense to put E2E in this quota. 👍🏻

**Comment by with-heart** [comment]
Yeah, go for it! The 2000 minutes limit is for private repositories. We'll likely never hit the free limits that exist: https://docs.github.com/en/actions/reference/usage-limits-billing-and-administration#usage-limits

**Comment by codingwithmanny** [comment]
Not sure if this would help, but I saw this show up in my work feed today.
 https://testing-library.com/docs/cypress-testing-library/intro/

**Comment by grothem** [comment]
Hey @fmoliveira, if you'd like any help with this, let me know!

**Comment by fmoliveira** [comment]
@with-heart Nice, I didn't spot that note!

@codingwithmanny Thank you, I'm definitely going to use it! 😃 

@grothem Sure, thank you so much!
