### ISSUE TITLE
Convert codebase to TypeScript

### ISSUE THREAD

**Issue by with-heart** [Developer-DAO/developer-dao#84]
Converting the codebase to TypeScript early on would give us immediate and long-term benefits:

- consistency in data/props
- improved DX
- integration with Chakra & other external library types
- ci type-check can save us effort, prevent bugs, etc.
- improved ability to refactor code

As with any technology, there's always a cost to contributors who aren't familiar with it. To make up for that, I'm more than happy to help onboard and get anyone who is JS-only up to speed with TS.

**Comment by miralsuthar** [comment]
Me and Nazeeh would like to work on this

**Comment by with-heart** [comment]
Go for it!
