### ISSUE TITLE
Document contributor patterns/expectations

### ISSUE THREAD

**Issue by with-heart** [Developer-DAO/developer-dao#9]
As a project grows, it's important to establish clear patterns and expectations for potential contributors in a single place. This allows new contributors to understand any special cases they need to be aware of that might affect their workflow, so they can be effective in working on the project from the get-go.

An example of a special case is #7. i18n is great and we should want that in the project, but it means that new contributors need to handle text/translations in a specific way. Having that documented could save them the trouble of not knowing that until after they open a PR.

For Chakra UI, we created [a `CONTRIBUTING.md` file](https://github.com/chakra-ui/chakra-ui/blob/main/CONTRIBUTING.md) which documents tools we use and how to use them, various npm scripts use for managing the project, the process for creating a PR, etc. 

I plan on opening a PR to create this file, but wanted to start with an issue to get feedback and see if anyone has any ideas for things to add to it.

**Comment by nheingit** [comment]
Would like to add a `.github` file where we can put a pull request template to ensure that we're following all of the steps outlined in the `CONTRIBUTING.md` file, and make PR's more standard and easy to read through.

**Comment by with-heart** [comment]
> Would like to add a `.github` file where we can put a pull request template to ensure that we're following all of the steps outlined in the `CONTRIBUTING.md` file, and make PR's more standard and easy to read through.

Ye, definitely agree with that! I LOVE issue forms and PR templates! 

I do want to avoid too much process too quickly though, as that can be more of a burden than it's worth at certain stages of a project's life. Not sure if that applies here, but just something to think about! 

If a PR template helps give us useful information that makes it easier to review the code, I'm totally down. Just not sure we even know what kind of useful information we need from a PR yet, ya know?
